checksumBehavior: throw

compressionLevel: mixed

enableColors: true

enableGlobalCache: false

enableImmutableInstalls: false

enableScripts: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 2880

npmPreapprovedPackages:
  - react
  - webpack
  - "@types/*"

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.10.3.cjs
