/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Play2048Wars: {
      address: "0x196dbcbb54b8ec4958c959d8949ebfe87ac2aaaf",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_entryFee",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "calculateScore",
          inputs: [
            {
              name: "board",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "score",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "currentRound",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "endGame",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "enterGame",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "entryFee",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "gameSessions",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
            {
              name: "initialBoard",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentBoard",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "score",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isActive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "startTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "movesPlayed",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getAllWinners",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCurrentRoundPool",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEntryFee",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getGameSession",
          inputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "game",
              type: "tuple",
              internalType: "struct Play2048Wars.GameSession",
              components: [
                {
                  name: "gameId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "player",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "initialBoard",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "currentBoard",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "score",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "isActive",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "startTime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "movesPlayed",
                  type: "uint8",
                  internalType: "uint8",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getGameStats",
          inputs: [],
          outputs: [
            {
              name: "totalGames",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "nextId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getInitialHash",
          inputs: [
            {
              name: "positionTile1",
              type: "uint8[]",
              internalType: "uint8[]",
            },
            {
              name: "positionTile2",
              type: "uint8[]",
              internalType: "uint8[]",
            },
          ],
          outputs: [
            {
              name: "hash",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getNextRoundPool",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPlayerGame",
          inputs: [
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "game",
              type: "tuple",
              internalType: "struct Play2048Wars.GameSession",
              components: [
                {
                  name: "gameId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "player",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "initialBoard",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "currentBoard",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "score",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "isActive",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "startTime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "movesPlayed",
                  type: "uint8",
                  internalType: "uint8",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTimeRemainingOfCurrentRound",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTopTenWinners",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isGameOver",
          inputs: [
            {
              name: "board",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "gameOver",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "isPlayer",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "isWinner",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextGameId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextRoundStart",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "playerGames",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
            {
              name: "initialBoard",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentBoard",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "score",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "isActive",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "startTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "movesPlayed",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "playersList",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "processBatchMoves",
          inputs: [
            {
              name: "directions",
              type: "uint8[]",
              internalType: "enum Lib2048WarsBoard.MoveDirection[]",
            },
            {
              name: "expectedBoards",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [
            {
              name: "success",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "finalBoard",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setNewEntryFee",
          inputs: [
            {
              name: "_entryFee",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "startGame",
          inputs: [
            {
              name: "initialBoard",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "gameId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "totalGamesPlayed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "validateBatchMoves",
          inputs: [
            {
              name: "startBoard",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "directions",
              type: "uint8[]",
              internalType: "enum Lib2048WarsBoard.MoveDirection[]",
            },
            {
              name: "expectedBoards",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          outputs: [
            {
              name: "isValid",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "errorIndex",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "validateMove",
          inputs: [
            {
              name: "previousBoard",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "direction",
              type: "uint8",
              internalType: "enum Lib2048WarsBoard.MoveDirection",
            },
            {
              name: "nextBoard",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "isValid",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "verifyInitialBoard",
          inputs: [
            {
              name: "initialBoard",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "isValid",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "winnersList",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "BatchMovesProcessed",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "gameId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "moveCount",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
            {
              name: "finalBoard",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameCompleted",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "gameId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "finalScore",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameEntered",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameOver",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "gameId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "GameStarted",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "gameId",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "initialBoard",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "NewRoundStarted",
          inputs: [],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "PlayerAssigned",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WinnerAssigned",
          inputs: [
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "Play2048Wars__BatchValidationFailed",
          inputs: [
            {
              name: "reason",
              type: "string",
              internalType: "string",
            },
          ],
        },
        {
          type: "error",
          name: "Play2048Wars__GameAlreadyStarted",
          inputs: [],
        },
        {
          type: "error",
          name: "Play2048Wars__GameNotStarted",
          inputs: [],
        },
        {
          type: "error",
          name: "Play2048Wars__InvalidBatchSize",
          inputs: [],
        },
        {
          type: "error",
          name: "Play2048Wars__InvalidInitialBoard",
          inputs: [],
        },
        {
          type: "error",
          name: "Play2048Wars__NotPlayer",
          inputs: [],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 14,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
